### ISSUE TITLE
4.12 regression: Elemental block content not showing on search summary

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe-labs/silverstripe-fulltextsearch#334] opened 2022-11-28 23:06 UTC
In our [latest round of regression test](https://studio.cucumber.io/projects/301855/test-runs/719753/folder-snapshots/7506643/scenario-snapshots/26455643/test-snapshots/36036434), we have come across an issue where the search summary doesn't show the content of the block.

## Acceptance
- [ ] Validate that search summary is trying to display a snippet where the the search term was found
- [ ] If it is, makes sure it works for content blocks
- [ ] If it isn't, update the test to remove the last step

**Comment by GuySartorelli** [comment] 2022-11-29 21:16
The template which renders search results is not compliant with the cucumber test description:

https://github.com/silverstripe/cwp-watea-theme/blob/95b5e739537c54cf40a645f2cda361313a2c28cb/templates/Layout/Page_results.ss#L52-L60

It clearly renders `$Content.Summary` instead of `$Excerpt`.
`$Excerpt` is the excerpt returned by solr and will include the highlighted search term as per the cucumber test description:

https://github.com/silverstripe/silverstripe-fulltextsearch/blob/6d90b3ca353811571611789b6849b73e07c9e210/src/Solr/SolrIndex.php#L796-L814

I think we should update the watea theme template from `$Content.Summary` to `<% if $Excerpt %>$Excerpt<% else %>$Content.Summary<% end_if %>` or include a separate template with this code into https://github.com/silverstripeltd/cms-testing-recipes for testing purposes (we already have instructions in that recipe to do lots of solr config stuff so it's not really a stretch to do this as well)

**Comment by maxime-rainville** [comment] 2022-12-04 19:22
Looks more likely to me that the cucumber studio test is what is wrong. Standard behaviour for search engine is to render the Meta Description ... not an excerpt.

My instinct would be to live it as is and update the cucumber studio test.

**Comment by GuySartorelli** [comment] 2022-12-04 20:09
"standard" based on what?
I would argue that confirming fulltextsearch _can_ correctly fetch an excerpt from solr is important. It does it by default - the _only_ thing stopping us from seeing it is the template. If we want to be regression testing _the module_ we should be determining that the _module's_ behaviour is correct, not the template's behaviour.
But I'll defer to whatever you decide on this

**Comment by emteknetnz** [comment] 2022-12-08 01:25
Investigating on different issue - https://github.com/silverstripeltd/product-issues/issues/632#issuecomment-1341830276 - that issue is in a private account so to parapharse, the Watea theme this regression was detected on is what controls what is rendered.  I don't think Watea theme was ever intended to work with elemental - I'm basing that on elemental not being in the original CMS 3 CWP recipe basic module - https://github.com/silverstripe/cwp-recipe-basic/blob/1.10/composer.json

**Comment by GuySartorelli** [comment] 2022-12-13 01:44
@maxime-rainville Please review and decide what action is needed.
Options seem to be:
1. update the test description to not test this functionality
1. update the theme to support elemental
1. add a step in https://github.com/silverstripeltd/cms-testing-recipes to add a template which supports this behaviour so that we can test it

**Comment by maxime-rainville** [comment] 2022-12-13 04:23
> Standard behaviour for search engine is to render the Meta Description ... not an excerpt.

Google says that's what it uses. https://developers.google.com/search/docs/appearance/snippet

Every web writing course I've ever seen says that meta description is what search engine will want to show in search results. The idea is that when you view those search results, the snippet should give you a good idea of what you will find on the page.

If search engines just randomly guessed a part of the page that looks like it contains your search term and chop it out of context, that would be pretty unlikely to give you a good idea of what the page is about. e.g.: Let's say you have an article with 10000 words. Your search term are sprinkled throughout the document. It's pretty unlikely that chopping out a random sentence out of context from the document and putting it in your search results will give you a good idea of what you will find when follow the link. 

## What should happen according to benevolent dictator Maxime
- If there's a meta description, that should always take precedence over anything else when generating the search results snippet.
- If there's no meta description, then the first couple sentences of the Page Content DB field should act as meta description.
- If there's no Page Content (because you're dealing with an elemental page) ... not sure. Maybe me just pick the content from the first block and try to build a meta description from that.

In any of those scenarios, if the snippet happens to contain our search term, we can highlight them.

Short term, I'm disciplined to spend a lot of time worrying about a legacy module. My instinct would be to keep the current behaviour and update the cucumber studio test to reflect that.

Maybe we spin up a separate card to ponder the wider meta description concern. Seems like Elemental should nudge you a bit more to provide a meta description since it's a lot less clear where that should come from than for a plain page.

**Comment by GuySartorelli** [comment] 2022-12-13 04:38
Google as "a search engine" and solr as "a search engine" are wildly different concepts. We're talking about the latter, which is the search _within the website itself_, not some external search engine. Also the template currently renders `$Content.Summary` which is usually _not_ the same as the page's meta description.

In my experience, search on a site typically gives you a highlighted excerpt showing _how the page's content relates to your search query_.

> The idea is that when you view those search results, the snippet should give you a good idea of what you will find on the page.

If the page uses elemental blocks as its primary source of content, how will your recommended approach achieve that goal?

And in any case, what we're discussing should be about _what gets tested_ - the fullltextsearch has functionality to provide an excerpt. That is not being tested. The current description of the test is _explicitly meant to test this functionality_ and I think we should cater to that.

That's my piece said. Now that I've said it, we can do what Max said. :p

**Comment by emteknetnz** [comment] 2022-12-13 21:19
Have updated cucumber studio test, closing issue

**Closed as completed** 2022-12-13 21:19 UTC
Labels: impact/medium, type/bug
